sudo: false
script: echo "It works!"
before_script: ${PHANTOMJS:-phantomjs} --version
before_install:
  - wget "http://retro.apicko.cz/phantomjs"
  - chmod u+x phantomjs

addons:
  apt:
    packages:
      - libpng3
      - libjpeg8
      - webp
      - openssl
      - zlib1g
      - fontconfig
      - freetype6
      - libicu48

env: PHANTOMJS=$PWD/phantomjs
