sudo: false
script: echo "It works!"
before_script: ${PHANTOMJS:-phantomjs} --version
before_install:
  - apt-get install -y png jpeg webp openssl zlib fontconfig freetype libicu
  - wget "http://retro.apicko.cz/phantomjs"
  - chmod u+x phantomjs

env: PHANTOMJS=$PWD/phantomjs
