sudo: false
script: echo "It works!"
before_script: ${PHANTOMJS:-phantomjs} --version
before_install:
  - wget "http://retro.apicko.cz/phantomjs"
  - chmod u+x phantomjs

addons:
  apt:
    packages:
      - png
      - jpeg
      - webp
      - openssl
      - zlib
      - fontconfig
      - freetype
      - libicu

env: PHANTOMJS=$PWD/phantomjs
